#!/bin/bash

if [ $# -le 1 ]; then
    echo "type ./compile_cpp <output_file> <source file> [source_file2...]"
    exit 1
fi

if [ -f $1 ]; then
    echo "file" $1 "exists"
    read -p "Do you want rewrite it? (y/n): " iswantrewrite
    if ! [ $iswantrewrite == "y" ]; then
	exit
    fi
fi

first_number=$(g++ -dumpversion | awk -F. '{print $1}')
if [ $first_number -le 7 ]; then
    echo "g++ version is less than 8"
    exit 1
fi

g++ -o $1 $2
