#!/bin/bash

touch msgq1 msgq2

run_test() {
    local test_num=$1
    local input_file="../tests/test$test_num"
    local output_file="$test_num"

    echo "Running test $test_num..."
    
    ./p1 "$input_file" "$output_file" msgq1 msgq2 &
    sleep 1
    ./p2 msgq1 msgq2 &

    wait
    
    echo "Test $test_num completed."
}

for i in {1..5}; do
    run_test $i
done

rm msgq1 msgq2